-- MySQL Script generated by MySQL Workbench
-- Sun Jul  2 18:03:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoIntegrador
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectoIntegrador` ;

-- -----------------------------------------------------
-- Schema ProyectoIntegrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoIntegrador` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoIntegrador` ;

-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `nombreProvincia` VARCHAR(100) NULL,
  `dispoHospitalaria` INT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Canton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Canton` (
  `idCanton` INT NOT NULL,
  `Homicidios` INT NULL,
  `nombreCanton` VARCHAR(100) NULL,
  `Provincia_idProvincia` INT NOT NULL,
  PRIMARY KEY (`idCanton`, `Provincia_idProvincia`),
  INDEX `fk_Canton_Provincia1_idx` (`Provincia_idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Canton_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `ProyectoIntegrador`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Ciudad` (
  `idCiudad` INT NOT NULL,
  `nombreCiudad` VARCHAR(100) NULL,
  `Canton_idCanton` INT NOT NULL,
  `Canton_Provincia_idProvincia` INT NOT NULL,
  PRIMARY KEY (`idCiudad`, `Canton_idCanton`, `Canton_Provincia_idProvincia`),
  INDEX `fk_Ciudad_Canton1_idx` (`Canton_idCanton` ASC, `Canton_Provincia_idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudad_Canton1`
    FOREIGN KEY (`Canton_idCanton` , `Canton_Provincia_idProvincia`)
    REFERENCES `ProyectoIntegrador`.`Canton` (`idCanton` , `Provincia_idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Vivienda` (
  `idVivienda` VARCHAR(60) NOT NULL,
  `fexp` VARCHAR(45) NULL,
  `upm` BIGINT(150) NULL,
  `periodo` INT NULL,
  `mes` INT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idVivienda`, `Ciudad_idCiudad`),
  INDEX `fk_Vivienda_Ciudad1_idx` (`Ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Vivienda_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `ProyectoIntegrador`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Hogar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Hogar` (
  `idHogar` VARCHAR(60) NOT NULL,
  `tipoVivienda` INT NULL,
  `formaTenenciaVivienda` INT NULL,
  `valorPagaArriendoMensual` INT NULL,
  `incluyeAguaArriendo` INT NULL,
  `incluyeLuzArriendo` INT NULL,
  `numCuartos` INT NULL,
  `numCuartosNegocio` INT NULL,
  `disponeHogarCocina` INT NULL,
  `numDormitorios` INT NULL,
  `viaAccesoPrincipalVivienda` INT NULL,
  `Vivienda_idVivienda` VARCHAR(60) NOT NULL,
  `Vivienda_Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idHogar`, `Vivienda_idVivienda`, `Vivienda_Ciudad_idCiudad`),
  INDEX `fk_Hogar_Vivienda1_idx` (`Vivienda_idVivienda` ASC, `Vivienda_Ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Hogar_Vivienda1`
    FOREIGN KEY (`Vivienda_idVivienda` , `Vivienda_Ciudad_idCiudad`)
    REFERENCES `ProyectoIntegrador`.`Vivienda` (`idVivienda` , `Ciudad_idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Materiales` (
  `materialCocina` INT NULL,
  `materialTechoCubierta` INT NULL,
  `estadoParedes` INT NULL,
  `estadoTecho` INT NULL,
  `materialPiso` INT NULL,
  `estadoPiso` INT NULL,
  `materialParedes` INT NULL,
  `Hogar_idHogar` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Hogar_idHogar`),
  CONSTRAINT `fk_Materiales_Hogar1`
    FOREIGN KEY (`Hogar_idHogar`)
    REFERENCES `ProyectoIntegrador`.`Hogar` (`idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`ServiciosBasicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`ServiciosBasicos` (
  `tipoServicioHigienico` INT NULL,
  `alternativaServicioHigienico` INT NULL,
  `servicioDucha` INT NULL,
  `tipoAlumbrado` INT NULL,
  `contieneMedidorAgua` INT NULL,
  `aguaJunta` INT NULL,
  `fuenteAgua` INT NULL,
  `sanitarioPrincipal` INT NULL,
  `aguaRecibida` INT NULL,
  `eliminacionBasura` INT NULL,
  `Hogar_idHogar` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Hogar_idHogar`),
  CONSTRAINT `fk_ServiciosBasicos_Hogar1`
    FOREIGN KEY (`Hogar_idHogar`)
    REFERENCES `ProyectoIntegrador`.`Hogar` (`idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Vehiculos` (
  `numMotos` INT NULL,
  `numVehiculos` INT NULL,
  `tieneMotos` INT NULL,
  `tieneVehiculos` INT NULL,
  `Hogar_idHogar` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Hogar_idHogar`),
  CONSTRAINT `fk_Vehiculos_Hogar1`
    FOREIGN KEY (`Hogar_idHogar`)
    REFERENCES `ProyectoIntegrador`.`Hogar` (`idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Combustible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Combustible` (
  `abastecimientoFrecuenteEcopais` INT NULL,
  `gastoCombustibleElectricidadEcopais` INT NULL,
  `abastecimientoFrecuenteElectricidad` INT NULL,
  `gastoCombustibleElectricidadElectricidad` INT NULL,
  `abastecimientoFrecuenteGas` INT NULL,
  `gastoCombustibleElectricidadGas` INT NULL,
  `abastecimientoFrecuenteSuper` INT NULL,
  `gastoCombustibleElectricidadSuper` INT NULL,
  `abastecimientoFrecuenteExtra` INT NULL,
  `abastecimientoFrecuenteDiesel` INT NULL,
  `gastoCombustibleElectricidadDiesel` INT NULL,
  `Vehiculos_Hogar_idHogar` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Vehiculos_Hogar_idHogar`),
  CONSTRAINT `fk_Combustible_Vehiculos1`
    FOREIGN KEY (`Vehiculos_Hogar_idHogar`)
    REFERENCES `ProyectoIntegrador`.`Vehiculos` (`Hogar_idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`Parroquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`Parroquia` (
  `conglomerado` INT NULL,
  `panelm` INT NULL,
  `estrato` INT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`Ciudad_idCiudad`),
  CONSTRAINT `fk_Parroquia_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `ProyectoIntegrador`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoIntegrador`.`CalidadVida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoIntegrador`.`CalidadVida` (
  `EmergenciasParr` INT NULL,
  `promSueldoDeseado` FLOAT NULL,
  `PorcenEstadoSalud` FLOAT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`Ciudad_idCiudad`),
  CONSTRAINT `fk_CalidadVida_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `ProyectoIntegrador`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaProv.csv'
INTO TABLE Provincia
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaCanton.csv'
INTO TABLE Canton
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaCiudad.csv'
INTO TABLE Ciudad
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaCalidad.csv'
INTO TABLE CalidadVida
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaParroquia.csv'
INTO TABLE Parroquia
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaVivienda.csv'
INTO TABLE Vivienda
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaHogar.csv'
INTO TABLE Hogar
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaServicios.csv'
INTO TABLE ServiciosBasicos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaMaterial.csv'
INTO TABLE Materiales
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaVehiculos.csv'
INTO TABLE Vehiculos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '/usr/local/mysql-8.0.32-macos13-arm64/Uploads/cargaCombustible.csv'
INTO TABLE Combustible
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

